//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using EFreshStoreCore.Model.Context;

namespace EFreshAdmin.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignOrder
    {
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        [Required(ErrorMessage = "Please select a delivery man")]
        public Nullable<long> DeliveryManId { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<System.DateTime> AssignedOn { get; set; }
        public Nullable<long> AssignedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual Order Order { get; set; }
    }
}
