//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using EFreshAdmin.Models.EntityModels;

namespace EFreshStore.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeghnaUser
    {
        public long Id { get; set; }

        [Required(ErrorMessage = "Please enter employee ID")]
        public string EmployeeId { get; set; }

        [Required(ErrorMessage = "Please enter employee name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter mobile no")]
        [RegularExpression(@"^01[1-9]\d{8}$", ErrorMessage = "Please enter a valid mobile no. Ex. 01xxxxxxxxx")]
        public string MobileNo { get; set; }

        [Required(ErrorMessage = "Please enter email address")]
        [RegularExpression(@"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", ErrorMessage = "Please enter a valid email")]
        public string Email { get; set; }
        public string Designation { get; set; }

       // [Required(ErrorMessage = "Please enter delivery address.")]
        public string DeliveryAddress1 { get; set; }
        public string DeliveryAddress2 { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> MeghnaDepartmentId { get; set; }
        public Nullable<long> MeghnaDesignationId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public virtual MeghnaDepartment MeghnaDepartment { get; set; }
        public virtual MeghnaDesignation MeghnaDesignation { get; set; }
        public virtual User User { get; set; }
    }
}
