//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using EFreshStore.Models.Context;

namespace EFreshStoreCore.Model.Context
{
    using System;

    public partial class OrderDetail
    {
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> ProductUnitId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        [Required(ErrorMessage = "Please enter packet quantity")]
        public Nullable<int> PacketQuantity { get; set; }

        public virtual Order Order { get; set; }
        public virtual ProductUnit ProductUnit { get; set; }
    }
}
