//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using EFreshStoreCore.Model.Context;

namespace EFreshStore.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductUnit()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductUnitPrices = new HashSet<ProductUnitPrice>();
        }
    
        public long Id { get; set; }

        [Required(ErrorMessage = "Please select product")]
        public Nullable<long> ProductId { get; set; }

        [Required(ErrorMessage = "Please enter stock keeping unit")]
        public string StockKeepingUnit { get; set; }

        [Required(ErrorMessage = "Please enter carton size")]
        public string CartonSize { get; set; }

        [Required(ErrorMessage = "Please enter carton size unit")]
        public string CartonSizeUnit { get; set; }

        [Required(ErrorMessage = "Please enter distributor price per carton")]
        public Nullable<decimal> DistributorPricePerCarton { get; set; }

        [Required(ErrorMessage = "Please enter trade price per carton")]
        public Nullable<decimal> TradePricePerCarton { get; set; }

        [Required(ErrorMessage = "Please enter maximum retail price")]
        public Nullable<decimal> MaximumRetailPrice { get; set; }

        [Required(ErrorMessage = "Please select effective date")]
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductUnitPrice> ProductUnitPrices { get; set; }
    }
}
