//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace EFreshStore.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanaWiseMasterDepot
    {
        public long Id { get; set; }

        [Required(ErrorMessage = "Please select master depot")]
        public Nullable<long> MasterDepotId { get; set; }

        [Required(ErrorMessage = "Please select thana")]
        public Nullable<long> ThanaId { get; set; }
    
        public virtual MasterDepot MasterDepot { get; set; }
        public virtual Thana Thana { get; set; }
    }
}
